kind: Deployment
apiVersion: apps/v1
metadata:
  name: poc-deployment
  labels:
    app: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc
  template:
    metadata:
      labels:
        app: poc
        version: v0.0.1
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: poc
        image: itlgdeveloper/poc-jenkins-bitbucket-hook:{{ .Values.tag }}
        ports:
        - containerPort: 80
